import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar/navbar";
import Sessionprovider from "@/components/session-provider";
import { Toast } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <main className=" max-w-7xl mx-auto p-5 space-y-12">
                  <Navbar/>
                    {children}
            </main>
            <Toaster/>  
        </ThemeProvider>
        <Sessionprovider/>
        </body>
    </html>
  );
}
